language: ruby
cache: bundler
services:
  - postgresql
jobs:
  include:
    - stage: build
      before_script:
        - psql -c "create database CoachHelper_test;" -U postgres
      script:
        - bundle exec rspec spec
        - bundle exec brakeman --quiet
        - bundle exec rubocop
stages:
  - build
